//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _TestApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;

    [Table(Name = "Pens")]
    public partial class Pen
    {
        [Column]
        public int PenId { get; set; }
        [Column]
        public string Description { get; set; }
        [Column]
        public Nullable<decimal> Price { get; set; }
        [Column]
        public Nullable<int> Quantity { get; set; }
        [Column]
        public string InkColor { get; set; }
    }
}
